//@const this is a comment for predict
//@return this is a comment for return type
predict#12345678 = SomeType;

---functions---

//@const this is a comment for function
//@param param1 this is a comment for param1
//@param param2 this is a comment for param2
//@return this is a comment for return type
function#12345678 param1:string param2:bool = SomeType;
functionNoFields#12345678 = SomeType;
functionWithoutComments#12345678 flags:# a:flags.1?true = SomeType;
