package codegen

import (
	"fmt"
	"github.com/xelaj/tl"

	"github.com/dave/jennifer/jen"
)

func Generate(s *tl.Schema) (string, error) {
	f := jen.NewFile("main")
	f.PackageComment("Code generated by tlgen. DO NOT EDIT.")

	for _, t := range s.TypePredicts() {
		f.Add(generateObjects(t))
	}

	f.Add(generateMakeRequesterFunc())

	for _, t := range s.Functions() {
		f.Add(generateRequestType(t))
		f.Line()
	}

	return fmt.Sprintf("%#v", f), nil
}
