package codegen

import (
	"fmt"
	"github.com/xelaj/tl"

	"github.com/dave/jennifer/jen"
	"github.com/quenbyako/ext/maps"
	"github.com/quenbyako/ext/slices"
)

func Generate(s *tl.Schema) (string, error) {
	f := jen.NewFile("main")
	f.PackageComment("Code generated by tlgen. DO NOT EDIT.")

	for _, name := range slices.SortFunc(maps.Keys(s.TypeDeclMap), func(a, b tl.Name) int { return a.Cmp(b) }) {
		f.Add(generateObjects(name, s.TypeDeclMap[name]))
	}

	f.Add(generateMakeRequesterFunc())

	for _, name := range slices.SortFunc(maps.Keys(s.FuncDeclMap), func(a, b tl.Name) int { return a.Cmp(b) }) {
		f.Add(generateRequestType(s.FuncDeclMap[name]))
		f.Line()
	}

	return fmt.Sprintf("%#v", f), nil
}
