name: Lint Go

on:
  push:
    branches:
      - master

jobs:
  goLint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.19.2'

      - name: Lint
        run: |
          gofmt -l -s .